### ISSUE TITLE
Type hinting of magic methods?

### ISSUE THREAD

**Issue by Wilt** [dg/ftp-php#8]
It is nice how you used php `__call` for mapping methods to `php` functions, but the disadvantage is that my code editor is not type hinting any of those magic methods. Would you at all be interested in a change where the methods are actually implemented in the `Ftp` class so that type hinting becomes supported?

**Comment by dg** [comment]
Better is to add anotations this way https://github.com/nette/utils/blob/master/src/Utils/Image.php#L25

**Comment by Wilt** [comment]
I added a [pull request](https://github.com/dg/ftp-php/pull/9) for this

**Comment by Wilt** [comment]
Not merging this?

**Comment by dg** [comment]
Merged, thanks
